### ISSUE TITLE
"Input string was not in a correct format."

### ISSUE THREAD

**Issue by PhoxLogic** [Davidobot/BetterJoy#483]
Every time I try to start BetterJoy, I get the titular "input string not in correct format" error as soon as it runs. The detailed report shows the following (I will leave the full log in a text file, this is a snippet):

> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at BetterJoyForCemu.JoyconManager.CheckForNewControllers()
   at BetterJoyForCemu.Program.Start()
   at BetterJoyForCemu.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

In addition to this, should I click "Continue" on the error popup, the program will start and act like it recognizes a single pro controller, regardless of whether or not I have one connected. As a result of all this, I cannot get a pro controller (or I'm assuming anything at all) to connect to the program. I have so far been able to replicate this on both 6.2 and 6.3. In case it's important, I will note I'm using Windows 7 and only have the ViGemBus driver installed (which should be all I need according to the readme).

Finally, here's the full error log I mentioned: [BetterJoyError.txt](https://github.com/Davidobot/BetterJoy/files/5080211/BetterJoyError.txt)

**Comment by Justyn83** [comment]
Hi PhoxLogic, 
thank you for your reply. I have installed Toshiba Bluetooth stack installed.
First Betterjoy worked for me but I must have messed up something. I deinstalled it and reinstalled it with restarts but it didnt solve the problem. I try to reinstall Toshiba Bluetooth stack maybe there is the problem ?

**Comment by PhoxLogic** [comment]
Well, what I was saying was that I think having that installed could have been _causing_ the problems, not solving them... but if you're getting a similar error with the Windows Bluetooth stack then I think the chances of that being true are... less likely. For now I guess I'll stick with using WiinUPro, if I ever need gyro for Cemu I'll get out a WiiMote or something. (Assuming that even works without having BetterJoy)
