### ISSUE TITLE
[BUG] .NET Framework Error: Unable to load DLL 'hidapi.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by Memebeters** [Davidobot/BetterJoy#798]
When I open the program, I receive an error stating the following:
Unable to load DLL 'hidapi.dll': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
Clicking on the "Add Controllers" button causes the same error to occur, and the GUI for connecting them never appears.

I have ViGEmBus and HidGuardian installed from the "Drivers" folder, so no issues there.
I have also ran as admin, so that isn't the issue.

I can't even get to the GUI to connect controllers, so controller info probably isn't necessary.

Here's the debug info if you need it:
System.DllNotFoundException: Unable to load DLL 'hidapi.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at BetterJoyForCemu.HIDapi.hid_enumerate(UInt16 vendor_id, UInt16 product_id)
   at BetterJoyForCemu._3rdPartyControllers.RefreshControllerList()
   at BetterJoyForCemu.Program.Start()
   at BetterJoyForCemu.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BetterJoyForCemu
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Gage/Documents/Tools/BetterJoy/BetterJoyForCemu.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
Nefarius.ViGEm.Client
    Assembly Version: 1.16.150.0
    Win32 Version: 1.16.150
    CodeBase: file:///C:/Users/Gage/Documents/Tools/BetterJoy/Nefarius.ViGEm.Client.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
WindowsInput
    Assembly Version: 6.1.0.0
    Win32 Version: 6.1.0.0
    CodeBase: file:///C:/Users/Gage/Documents/Tools/BetterJoy/WindowsInput.DLL
----------------------------------------

**Comment by jongmyoungkim** [comment]
Install Visual C++ 2015-2019 from MS's website: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.

**Comment by vaguerant** [comment]
I'm in this situation as well, but none of the advice is working for me. My PC is running Windows 10 (x64) and I already have the Visual C++ 2015-2019 Redistributables (32- **and** 64-bit) installed. I've also tried deleting and reinstalling them (and restarting) just in case, but that didn't help either. I'm out of ideas.

**Comment by Mr-Sheep** [comment]
I tried to install VC++ 2015-2022 from microsoft, but it did not work. So i simply downloeded the hidapi.dll file from the [libusb/hidapi repo](https://github.com/libusb/hidapi/releases) and placed it under `C:\\Windows\System32`
